apiVersion: openlakeforge.io/v1alpha1
kind: DeploymentProfile

metadata:
  name: openlakeforge-acceptance

spec:
  provider:
    type: aws
    region: eu-west-3
  preset: full
  stages:
    dev:
      enabled: true
    prod:
      enabled: true
