name: marketing_campaign_performance
version: "1.0.0"
config-version: 2

profile: marketing_campaign_performance

model-paths: ["models"]
macro-paths: []
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  marketing_campaign_performance:
    +database: "{{ env_var('OPENLAKEFORGE_CATALOG_NAME', 'lakehouse_dev') }}"
    +materialized: table
    +on_table_exists: replace
    +meta:
      dagster:
        group: marketing_campaign_performance
    gold:
      +tags: ["marketing", "campaign_performance", "gold"]
