"""Build, publish, and verify the immutable `ProjectRevision` (#154).

A project revision identifies the complete promotable data project by
content: descriptors, Floe contracts, dbt, Dagster orchestration code, report
assets when present, the project-code image digest, and the distribution
version. It intentionally excludes `openlakeforge.yaml` (deployment intent,
not project content) and every stage-rendered Floe artifact (manifests,
profiles) -- those embed physical bucket names, namespaces, and secret
references and are regenerated per stage by #115. See ADR 0012.

Unlike `olf.revision` (the v0.2 Floe runtime-artifact revision, now under
`olf floe revision`), this revision never touches a rendered Floe manifest --
only the checked-in domain contract that produces one.
"""

from __future__ import annotations

import hashlib
import json
import re
from collections.abc import Callable, Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from olf import revision as floe_revision
from olf.artifact_store import RevisionStore, publish_immutable, read_required
from olf.project import ProjectSpec, validate_project

MANIFEST_API_VERSION = "openlakeforge.io/v1alpha1"
MANIFEST_KIND = "ProjectRevision"
REVISION_PREFIX = "project/revisions"
SIDECAR_NAME = "PROJECT-REVISION.json"

# ADR 0012's complete promotion unit. "reports" is the only optional member
# (present only when the project declares at least one dashboard); every
# other name here must always be present, or a sidecar with, say, only
# "image"+"distribution" would pass every other check while never covering
# any actual project artifact -- `verify()` skips both of those by design.
_REQUIRED_COMPONENT_NAMES = frozenset({"descriptors", "floe", "dbt", "dagster", "image", "distribution"})
_ALL_COMPONENT_NAMES = _REQUIRED_COMPONENT_NAMES | {"reports"}

# Mirrors .gitignore's "dbt local artifacts" block: these are generated by
# running dbt locally (`dbt deps`/`dbt parse`/`dbt build`), not part of the
# tracked project. Without excluding them, an identical tracked source tree
# produces a different revision depending on whether dbt happened to run
# locally first, and a local log file could spuriously trip the forbidden-
# value scan.
_EXCLUDED_DIR_NAMES = frozenset({"target", "dbt_packages", "logs", "__pycache__", ".venv", ".pytest_cache"})
_EXCLUDED_FILE_NAMES = frozenset({".user.yml", "package-lock.yml"})
_DIGEST_TAG_PATTERN = re.compile(r"@sha256:[0-9a-f]{64}$")
# Deliberately narrow: an env var *name* (AWS_REGION, AWS_SECRET_ACCESS_KEY)
# or a Kubernetes Secret *reference* (secret_name:/secretRef/client_secret_key)
# is the sanctioned way credentials reach a pod (AGENTS "No credentials in
# generated artifacts") and must never be flagged -- only a concrete,
# unambiguous physical value is. `s3://` is always a physical bucket
# location (ADR 0004: object-store names never appear in project source).
# `http://` (not `https://`) is this codebase's own convention for every
# in-cluster stage endpoint (`http://seaweedfs-s3:8333`,
# `http://polaris:8181/...`; see `olf/floe.py`), so it is a strong signal
# without rejecting legitimate external HTTPS API references a Bronze
# source might declare. `AKIA...` is the fixed-format AWS access key ID
# prefix -- a real credential value, not a name. The assignment pattern
# below matches only a bare credential noun used as its own key
# (`password: ...`, `api_token = "..."`, `"password": "..."`) -- `\b` word
# boundaries mean it cannot match inside a compound reference identifier
# like `secret_name`, `secretRef`, or `client_secret_key`, since `_`/mixed-
# case letters are all regex word characters with no boundary between them.
# An optional quote is allowed on both sides of the key (JSON quotes it;
# YAML/Python usually don't) so `"password":` isn't missed just because a
# closing quote sits between the key and the colon. The negative lookahead
# excludes the sanctioned env-lookup/substitution forms this codebase and
# ordinary Python/YAML use to read a secret at runtime rather than embed
# it: `${VAR}`/`$VAR`, `os.environ[...]`/`os.getenv(...)`, and any
# `name.name(...)`-shaped call (`config.env(...)`, `environ.get(...)`).
#
# That exclusion has its own gap, closed by the second pattern below: it
# exempts an entire call or substitution expression, including whatever
# sits inside it -- so a literal secret smuggled in as the *default/
# fallback* argument (`os.getenv("TOKEN", "sk-live-...")`,
# `${DB_PASSWORD:-hunter2}`) would otherwise pass clean. A bare reference
# with no default (`os.getenv("TOKEN")`, `${DB_PASSWORD}`) has nothing to
# smuggle and still isn't flagged; a reference *with* one is.
_CREDENTIAL_NOUN = (
    r"(?:password|passwd|token|secret|api[_-]?key|api[_-]?token|access[_-]?token|"
    r"client[_-]?secret|private[_-]?key)"
)
_FORBIDDEN_VALUE_PATTERNS = (
    re.compile(r"s3://", re.IGNORECASE),
    re.compile(r"http://"),
    re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
    re.compile(
        rf"(?i)\b{_CREDENTIAL_NOUN}\b['\"]?\s*[:=]\s*"
        r"(?!\$|os\.environ|os\.getenv|[\w.]+\()"
        r"['\"]?[^\s'\"]{4,}"
    ),
    re.compile(
        rf"(?i)\b{_CREDENTIAL_NOUN}\b['\"]?\s*[:=]\s*"
        r"(?:[\w.]+\(\s*['\"][^'\"]+['\"]\s*,\s*['\"][^'\"]{4,}['\"]"  # call with a default argument
        r"|\$\{?\w+\}?:-['\"]?[^\s'\"}]{4,})"  # ${VAR:-default} shell substitution
    ),
)


class ProjectRevisionError(RuntimeError):
    """A project revision cannot be built, published, or verified safely."""


@dataclass(frozen=True)
class ComponentEntries:
    """One named component of the project and the content digest of each of its files."""

    name: str
    entries: dict[str, str]

    def to_dict(self) -> dict[str, object]:
        return {"name": self.name, "entries": dict(sorted(self.entries.items()))}

    @classmethod
    def from_dict(cls, payload: Any) -> ComponentEntries:
        if (
            not isinstance(payload, dict)
            or not isinstance(payload.get("name"), str)
            or not isinstance(payload.get("entries"), dict)
            or not all(
                isinstance(key, str) and isinstance(digest, str) for key, digest in payload["entries"].items()
            )
        ):
            raise ProjectRevisionError(f"malformed component entry: {payload!r}")
        return cls(name=payload["name"], entries=dict(payload["entries"]))


@dataclass(frozen=True)
class ProjectRevisionManifest:
    """The frozen, content-addressed identity of one complete data project."""

    project_name: str
    distribution_version: str
    project_code_image: str
    components: tuple[ComponentEntries, ...]
    revision: str

    def to_json(self) -> str:
        return (
            json.dumps(
                {
                    "apiVersion": MANIFEST_API_VERSION,
                    "kind": MANIFEST_KIND,
                    "schema_version": 1,
                    "project_name": self.project_name,
                    "distribution_version": self.distribution_version,
                    "project_code_image": self.project_code_image,
                    "components": [component.to_dict() for component in self.components],
                    "revision": self.revision,
                },
                indent=2,
                sort_keys=True,
            )
            + "\n"
        )

    @classmethod
    def from_json(cls, value: str) -> ProjectRevisionManifest:
        try:
            payload = json.loads(value)
        except json.JSONDecodeError as exc:
            raise ProjectRevisionError(f"malformed {SIDECAR_NAME}: {exc}") from exc
        if not isinstance(payload, dict):
            raise ProjectRevisionError(f"malformed {SIDECAR_NAME}: expected a JSON object")
        if payload.get("apiVersion") != MANIFEST_API_VERSION or payload.get("kind") != MANIFEST_KIND:
            raise ProjectRevisionError(
                f"unsupported {SIDECAR_NAME} apiVersion/kind: "
                f"{payload.get('apiVersion')!r}/{payload.get('kind')!r}"
            )
        components_payload = payload.get("components")
        if not isinstance(components_payload, list):
            raise ProjectRevisionError(f"malformed {SIDECAR_NAME}: 'components' must be an array")
        try:
            manifest = cls(
                project_name=payload["project_name"],
                distribution_version=payload["distribution_version"],
                project_code_image=payload["project_code_image"],
                components=tuple(ComponentEntries.from_dict(item) for item in components_payload),
                revision=payload["revision"],
            )
        except KeyError as exc:
            raise ProjectRevisionError(f"malformed {SIDECAR_NAME}: missing {exc}") from exc
        manifest.validate()
        return manifest

    def validate(self) -> None:
        # A duplicate component name is otherwise exploitable: `component()`
        # returns the first match (read by the cross-checks below) while
        # `_aggregate_components`'s dict-comprehension flattening keeps the
        # last match per overlapping key (read by the digest check) -- a
        # sidecar with two "image" components could put a mutable/legit
        # value first (matching a forged top-level field) and the value the
        # digest was actually computed from last, passing every check below
        # while `component("image")` reports the forged one.
        names = [component.name for component in self.components]
        if len(names) != len(set(names)):
            duplicates = sorted({name for name in names if names.count(name) > 1})
            raise ProjectRevisionError(
                f"revision sidecar declares duplicate component name(s): {', '.join(duplicates)}."
            )
        name_set = set(names)
        missing = _REQUIRED_COMPONENT_NAMES - name_set
        if missing:
            raise ProjectRevisionError(
                f"revision sidecar is missing required component(s): {', '.join(sorted(missing))}."
            )
        unknown = name_set - _ALL_COMPONENT_NAMES
        if unknown:
            raise ProjectRevisionError(
                f"revision sidecar declares unknown component(s): {', '.join(sorted(unknown))}."
            )
        actual = _aggregate_components(self.components)
        if self.revision != actual:
            raise ProjectRevisionError(
                f"revision sidecar declares {self.revision}, but its components aggregate to {actual}."
            )
        # The `distribution_version`/`project_code_image` top-level fields are
        # convenience duplicates of the `distribution`/`image` components --
        # the aggregate above only covers `components`, so a sidecar edited
        # to change a top-level field alone (leaving components and the
        # revision digest untouched) would otherwise pass every other check
        # while `verify`'s compatibility gate and consumers read the
        # unbound top-level value. Cross-check both explicitly.
        image_component = self.component("image")
        if image_component is None or image_component.entries.get("project-code") != self.project_code_image:
            raise ProjectRevisionError(
                f"project_code_image {self.project_code_image!r} does not match the manifest's image component."
            )
        distribution_component = self.component("distribution")
        if distribution_component is None or distribution_component.entries.get("version") != self.distribution_version:
            raise ProjectRevisionError(
                f"distribution_version {self.distribution_version!r} does not match the manifest's "
                "distribution component."
            )
        # The JSON Schema also enforces this, but only runs during a local
        # `olf project build` (see manifest_schema_errors); a hand-crafted or
        # corrupted-but-internally-consistent sidecar read straight off the
        # store bypasses it entirely, so the hand-rolled model must enforce
        # it too -- a self-consistent manifest pointing at a mutable tag is
        # still not an immutable revision.
        if not is_digest_pinned(self.project_code_image):
            raise ProjectRevisionError(
                f"project_code_image {self.project_code_image!r} is not digest-pinned."
            )
        _reject_runtime_values(self.to_json())

    def component(self, name: str) -> ComponentEntries | None:
        return next((component for component in self.components if component.name == name), None)


def revision_prefix(revision: str) -> str:
    digest = _revision_digest(revision)
    return f"{REVISION_PREFIX}/sha256/{digest}"


def sidecar_key(revision: str) -> str:
    return f"{revision_prefix(revision)}/{SIDECAR_NAME}"


def _revision_digest(revision: str) -> str:
    match = re.fullmatch(r"sha256:([0-9a-f]{64})", revision)
    if not match:
        raise ProjectRevisionError(f"invalid revision {revision!r}; expected sha256:<64 lowercase hex characters>.")
    return match.group(1)


def _aggregate_components(components: Iterable[ComponentEntries]) -> str:
    flattened = {
        f"{component.name}/{key}": digest for component in components for key, digest in component.entries.items()
    }
    if not flattened:
        raise ProjectRevisionError("cannot compute a revision for an empty project.")
    return floe_revision.aggregate_revision(flattened)


def manifest_schema_errors(payload: dict[str, Any], *, schema_root: Path) -> list[str]:
    """Validate a rendered manifest against its versioned JSON Schema.

    Mirrors `olf.contracts_check.descriptor_schema_errors`/
    `profile_schema_errors`: the hand-rolled model above and this schema
    validate independently, and neither substitutes for the other.
    """
    import jsonschema

    schema_path = schema_root / "project-revision.schema.json"
    schema = json.loads(schema_path.read_text(encoding="utf-8"))
    validator = jsonschema.Draft202012Validator(schema)
    errors = sorted(validator.iter_errors(payload), key=lambda error: list(error.absolute_path))
    return [
        f"schema violation at {'/'.join(str(part) for part in error.absolute_path) or '<root>'}: {error.message}"
        for error in errors
    ]


def _reject_runtime_values(rendered_json: str) -> None:
    for pattern in _FORBIDDEN_VALUE_PATTERNS:
        match = pattern.search(rendered_json)
        if match:
            raise ProjectRevisionError(
                f"project revision manifest contains a stage-bound value ({match.group(0)!r}); "
                "target-stage endpoints and credentials must never enter a promotable revision."
            )


def _reject_runtime_bytes(relative_key: str, content: bytes) -> None:
    """Scan one component file's actual content, not just the rendered manifest.

    `_reject_runtime_values` only sees paths, digests, and the image/
    distribution fields -- a stage-bound endpoint or credential embedded
    inside a frozen file's own content (a dbt profile, a Floe contract) would
    otherwise publish successfully. Decoded leniently: a non-UTF-8 file (a
    binary asset) cannot contain a matching text pattern either way.
    """
    text = content.decode("utf-8", errors="ignore")
    for pattern in _FORBIDDEN_VALUE_PATTERNS:
        match = pattern.search(text)
        if match:
            raise ProjectRevisionError(
                f"{relative_key} contains a stage-bound value ({match.group(0)!r}); "
                "target-stage endpoints and credentials must never enter a promotable revision."
            )


def _content_hash(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def _hash_and_scan(relative_key: str, path: Path, *, project_root: Path) -> str:
    # A symlinked component file can point anywhere on the host: reading it
    # would hash and publish arbitrary host content under the revision's
    # own key, and make the same tracked project produce a different
    # revision on a different machine. `rglob` does not recurse into a
    # symlinked directory it *encounters mid-walk*, but a component *root*
    # that is itself a symlink (e.g. `.../dbt` replaced with a link) is
    # followed by `_walk_files`'s own `is_dir()` check -- its contents are
    # then real, non-symlink files whose *resolved* location is still
    # outside `project_root`, which only the containment check below
    # catches; a leaf-only `is_symlink()` check would miss it entirely.
    if path.is_symlink():
        raise ProjectRevisionError(
            f"{relative_key} is a symlink; project revision inputs must be regular files."
        )
    resolved = path.resolve()
    if not resolved.is_relative_to(project_root.resolve()):
        raise ProjectRevisionError(f"{relative_key} resolves outside the project root ({resolved}).")
    content = path.read_bytes()
    _reject_runtime_bytes(relative_key, content)
    return _content_hash(content)


def _walk_files(root: Path) -> list[Path]:
    if not root.is_dir():
        return []
    return sorted(
        path
        for path in root.rglob("*")
        if path.is_file()
        and path.name not in _EXCLUDED_FILE_NAMES
        and not any(part in _EXCLUDED_DIR_NAMES for part in path.relative_to(root).parts)
    )


def _relative_key(project: ProjectSpec, path: Path) -> str:
    return path.relative_to(project.root).as_posix()


def _descriptors_component(project: ProjectSpec, inventory: Any) -> ComponentEntries:
    paths = [project.lakehouse_path]
    for source in inventory.sources:
        paths.append(project.bronze_root / source.name / "source.yaml")
    entries = {
        (key := _relative_key(project, path)): _hash_and_scan(key, path, project_root=project.root)
        for path in paths
    }
    return ComponentEntries("descriptors", entries)


def _floe_component(project: ProjectSpec) -> ComponentEntries:
    from olf.deployment.errors import DeploymentPreconditionError
    from olf.deployment.floe_manifests import _validate_one_config_per_domain, discover_floe_configs

    configs = discover_floe_configs(project.root)
    try:
        # A stray extra config in a domain's contracts directory isn't
        # caught by `validate_project` (it checks required paths exist, not
        # that nothing extra does), but the deploy path's own manifest
        # generation rejects it -- reuse that check here so a build never
        # advertises a revision #115 could not later activate.
        _validate_one_config_per_domain(configs)
    except DeploymentPreconditionError as exc:
        raise ProjectRevisionError(str(exc)) from exc
    entries = {
        (key := _relative_key(project, path)): _hash_and_scan(key, path, project_root=project.root)
        for path in configs
    }
    return ComponentEntries("floe", entries)


def _dbt_component(project: ProjectSpec, inventory: Any) -> ComponentEntries:
    entries: dict[str, str] = {}
    for product in inventory.products:
        for path in _walk_files(project.gold_root / product.id / "dbt"):
            key = _relative_key(project, path)
            entries[key] = _hash_and_scan(key, path, project_root=project.root)
    return ComponentEntries("dbt", entries)


def _dagster_component(project: ProjectSpec, inventory: Any) -> ComponentEntries:
    paths: list[Path] = []
    for product in inventory.products:
        paths.append(project.pipelines_root / f"{product.id}.py")
    for source in inventory.sources:
        paths.append(project.bronze_root / source.name / "dlt" / f"{source.name}.py")
    entries: dict[str, str] = {}
    for path in paths:
        if not path.is_file():
            continue
        key = _relative_key(project, path)
        entries[key] = _hash_and_scan(key, path, project_root=project.root)
    return ComponentEntries("dagster", entries)


def _reports_component(project: ProjectSpec, inventory: Any) -> ComponentEntries | None:
    if not inventory.dashboards:
        return None
    entries: dict[str, str] = {}
    for dashboard in inventory.dashboards:
        for path in _walk_files(project.root / dashboard.report_source_dir):
            key = _relative_key(project, path)
            entries[key] = _hash_and_scan(key, path, project_root=project.root)
    return ComponentEntries("reports", entries)


def is_digest_pinned(image: str) -> bool:
    return bool(_DIGEST_TAG_PATTERN.search(image))


def _default_resolve_image_digest(image: str) -> str:
    from olf.deployment.engine import Toolkit

    tools = Toolkit.default()
    result = tools.docker.image_inspect(image, check=False)
    if not result.ok:
        raise ProjectRevisionError(
            f"cannot inspect image {image!r} (not present locally); "
            "pull/build it first, or pass a digest-pinned reference."
        )
    try:
        payload = json.loads(result.stdout)
        entry = payload[0]
    except (json.JSONDecodeError, IndexError, TypeError) as exc:
        raise ProjectRevisionError(f"cannot inspect image {image!r}: {exc}") from exc
    # An image tagged or pushed under more than one repository (a common
    # `docker tag`/multi-registry-push outcome) can have several
    # RepoDigests -- only the one matching the *requested* repository is a
    # correct resolution of `--image`; returning an arbitrary one could
    # silently point the revision at an unrelated or target-inaccessible
    # registry even though the requested repository had a valid digest.
    requested_repository = image.split("@", 1)[0].rsplit(":", 1)[0]
    for repo_digest in entry.get("RepoDigests") or ():
        if is_digest_pinned(repo_digest) and repo_digest.split("@", 1)[0] == requested_repository:
            return repo_digest
    # Docker's `Id` is the local image *config* digest, not the registry
    # manifest digest a `repository@sha256:...` reference resolves through a
    # pull. Synthesizing one from `Id` would pass the digest-pinned regex
    # but be unpullable during promotion -- require an actual `RepoDigest`,
    # which only exists once the image has been pushed to (or pulled from)
    # a registry.
    raise ProjectRevisionError(
        f"image {image!r} has no registry digest (RepoDigests) for repository {requested_repository!r}; "
        "push it to that repository first, or pass an explicit digest-pinned reference. "
        "A local image config Id is not a pullable digest."
    )


def resolve_image_digest(image: str, *, resolver: Callable[[str], str] | None = None) -> str:
    """Return a digest-pinned image reference, resolving a local/registry tag if needed."""
    if is_digest_pinned(image):
        return image
    resolve = resolver or _default_resolve_image_digest
    resolved = resolve(image)
    if not is_digest_pinned(resolved):
        raise ProjectRevisionError(f"image {image!r} did not resolve to a digest-pinned reference: {resolved!r}")
    return resolved


def build_project_revision(
    project: ProjectSpec,
    *,
    image: str,
    distribution_version: str,
    resolve_image_digest_with: Callable[[str], str] | None = None,
) -> ProjectRevisionManifest:
    """Compute the frozen, content-addressed revision for one writable project.

    Refuses to build from an invalid project: a revision that omits a
    declared asset, or that freezes a broken descriptor, is worse than no
    revision at all.
    """
    from openlakeforge_domain import load_lakehouse_inventory

    report = validate_project(project)
    if not report.ok:
        failures = "; ".join(f"{check.name}: {check.detail}" for check in report.checks if not check.ok)
        raise ProjectRevisionError(f"project at {project.root} is not valid: {failures}")

    inventory = load_lakehouse_inventory(project.root)
    pinned_image = resolve_image_digest(image, resolver=resolve_image_digest_with)

    components = [
        _descriptors_component(project, inventory),
        _floe_component(project),
        _dbt_component(project, inventory),
        _dagster_component(project, inventory),
    ]
    reports = _reports_component(project, inventory)
    if reports is not None:
        components.append(reports)
    components.append(ComponentEntries("image", {"project-code": pinned_image}))
    components.append(ComponentEntries("distribution", {"version": distribution_version}))

    manifest = ProjectRevisionManifest(
        project_name=inventory.name,
        distribution_version=distribution_version,
        project_code_image=pinned_image,
        components=tuple(components),
        revision=_aggregate_components(components),
    )
    _reject_runtime_values(manifest.to_json())
    schema_root = project.schema_root
    if schema_root.is_dir():
        schema_errors = manifest_schema_errors(json.loads(manifest.to_json()), schema_root=schema_root)
        if schema_errors:
            raise ProjectRevisionError(f"built manifest violates its schema: {'; '.join(schema_errors)}")
    return manifest


def publish(store: RevisionStore, manifest: ProjectRevisionManifest, project: ProjectSpec) -> ProjectRevisionManifest:
    """Publish every entry a manifest declares under its immutable revision prefix.

    Publishes file content, not just digests, so `inspect`/`verify` can run
    against the published revision without a source checkout. Re-reads each
    file from `project.root` rather than reusing `build_project_revision`'s
    in-memory bytes, so every reread is checked against the digest the
    manifest already declared before anything is written: a file changed on
    disk between build and publish must fail closed here, not silently
    publish drifted content under a prefix whose sidecar claims a different
    digest.
    """
    from olf.artifact_store import ArtifactStoreError

    prefix = revision_prefix(manifest.revision)
    try:
        for component in manifest.components:
            if component.name in {"image", "distribution"}:
                continue
            for relative_key, expected_digest in component.entries.items():
                path = project.root / relative_key
                content = path.read_bytes()
                actual_digest = _content_hash(content)
                if actual_digest != expected_digest:
                    raise ProjectRevisionError(
                        f"{relative_key} changed on disk since the revision was built: "
                        f"now hashes to {actual_digest}, but the manifest declares {expected_digest}. "
                        "Rebuild the revision before publishing."
                    )
                publish_immutable(
                    store, f"{prefix}/{component.name}/{relative_key}", content, content_type=_content_type(path)
                )
        publish_immutable(
            store, sidecar_key(manifest.revision), manifest.to_json().encode("utf-8"), content_type="application/json"
        )
    except ArtifactStoreError as exc:
        raise ProjectRevisionError(str(exc)) from exc
    return manifest


def inspect(store: RevisionStore, revision: str) -> ProjectRevisionManifest:
    """Read a published manifest without verifying every referenced object."""
    from olf.artifact_store import ArtifactStoreError

    try:
        content = read_required(store, sidecar_key(revision))
    except ArtifactStoreError as exc:
        raise ProjectRevisionError(str(exc)) from exc
    manifest = ProjectRevisionManifest.from_json(content.decode("utf-8"))
    if manifest.revision != revision:
        raise ProjectRevisionError(
            f"sidecar at {sidecar_key(revision)} declares {manifest.revision}, not requested {revision}."
        )
    return manifest


def verify(
    store: RevisionStore, revision: str, *, running_distribution_version: str | None = None
) -> ProjectRevisionManifest:
    """Verify manifest self-consistency, the compatibility gate, and every published object's digest."""
    from olf.artifact_store import ArtifactStoreError

    manifest = inspect(store, revision)
    if running_distribution_version is not None and manifest.distribution_version != running_distribution_version:
        raise ProjectRevisionError(
            f"revision {revision} was built against distribution {manifest.distribution_version!r}, "
            f"incompatible with the running distribution {running_distribution_version!r}."
        )
    prefix = revision_prefix(revision)
    for component in manifest.components:
        if component.name in {"image", "distribution"}:
            continue
        for relative_key, expected_digest in component.entries.items():
            key = f"{prefix}/{component.name}/{relative_key}"
            try:
                actual_digest = hashlib.sha256(read_required(store, key)).hexdigest()
            except ArtifactStoreError as exc:
                raise ProjectRevisionError(str(exc)) from exc
            if actual_digest != expected_digest:
                raise ProjectRevisionError(
                    f"artifact {relative_key} in component {component.name} of revision {revision} "
                    f"hashes to {actual_digest}, expected {expected_digest}."
                )
    return manifest


def _content_type(path: Path) -> str:
    if path.suffix in {".yml", ".yaml"}:
        return "application/x-yaml"
    if path.suffix == ".json":
        return "application/json"
    if path.suffix == ".py":
        return "text/x-python"
    return "application/octet-stream"
