name: sales_customer_health
version: "1.0.0"
config-version: 2

profile: sales_customer_health

model-paths: ["models"]
macro-paths: []
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  sales_customer_health:
    +database: lakehouse_dev
    +materialized: iceberg_table
    +meta:
      dagster:
        group: sales_customer_health
    gold:
      +tags: ["sales", "customer_health", "gold"]
