"""Canonical provider-neutral lakehouse descriptors and inventory."""

from __future__ import annotations

from .descriptors import (
    DOMAIN_API_VERSION,
    DOMAIN_KIND,
    LAKEHOUSE_API_VERSION,
    LAKEHOUSE_KIND,
    LEGACY_DOMAIN_API_VERSION,
    SOURCE_API_VERSION,
    SOURCE_KIND,
    DomainDescriptorError,
    LakehouseDescriptorError,
    load_domain_descriptor,
    load_lakehouse_descriptor,
    load_source_descriptor,
    validate_domain_descriptor,
    validate_lakehouse_descriptor,
    validate_source_descriptor,
)
from .inventory import (
    ArtifactPrefixes,
    CatalogNamespace,
    Dashboard,
    Domain,
    DomainInventory,
    LakehouseInventory,
    PhysicalInventory,
    PhysicalProductNames,
    Product,
    Source,
    Table,
    inventory_for,
    load_domain_inventory,
    load_domain_inventory_from_descriptors,
    load_lakehouse_inventory,
    load_lakehouse_inventory_from_descriptors,
)

__all__ = [
    "DOMAIN_API_VERSION",
    "DOMAIN_KIND",
    "LAKEHOUSE_API_VERSION",
    "LAKEHOUSE_KIND",
    "LEGACY_DOMAIN_API_VERSION",
    "SOURCE_API_VERSION",
    "SOURCE_KIND",
    "ArtifactPrefixes",
    "CatalogNamespace",
    "Dashboard",
    "Domain",
    "DomainDescriptorError",
    "DomainInventory",
    "LakehouseDescriptorError",
    "LakehouseInventory",
    "PhysicalInventory",
    "PhysicalProductNames",
    "Product",
    "Source",
    "Table",
    "inventory_for",
    "load_domain_descriptor",
    "load_domain_inventory",
    "load_domain_inventory_from_descriptors",
    "load_lakehouse_descriptor",
    "load_lakehouse_inventory",
    "load_lakehouse_inventory_from_descriptors",
    "load_source_descriptor",
    "validate_domain_descriptor",
    "validate_lakehouse_descriptor",
    "validate_source_descriptor",
]