"""Canonical provider-neutral lakehouse descriptors and inventory."""

from __future__ import annotations

from .descriptors import (
    LAKEHOUSE_API_VERSION,
    LAKEHOUSE_KIND,
    SOURCE_API_VERSION,
    SOURCE_KIND,
    LakehouseDescriptorError,
    load_lakehouse_descriptor,
    load_source_descriptor,
    validate_lakehouse_descriptor,
    validate_source_descriptor,
)
from .inventory import (
    ArtifactPrefixes,
    CatalogNamespace,
    Dashboard,
    Domain,
    LakehouseInventory,
    PhysicalInventory,
    PhysicalDomainNames,
    PhysicalProductNames,
    PhysicalSourceNames,
    Product,
    GoldTable,
    SilverTable,
    SourceResource,
    Source,
    Table,
    inventory_for,
    load_lakehouse_inventory,
    load_lakehouse_inventory_from_descriptors,
    load_transitional_lakehouse_inventory,
)

__all__ = [
    "LAKEHOUSE_API_VERSION",
    "LAKEHOUSE_KIND",
    "SOURCE_API_VERSION",
    "SOURCE_KIND",
    "ArtifactPrefixes",
    "CatalogNamespace",
    "Dashboard",
    "Domain",
    "LakehouseDescriptorError",
    "LakehouseInventory",
    "PhysicalInventory",
    "PhysicalDomainNames",
    "PhysicalProductNames",
    "PhysicalSourceNames",
    "Product",
    "GoldTable",
    "SilverTable",
    "SourceResource",
    "Source",
    "Table",
    "inventory_for",
    "load_lakehouse_descriptor",
    "load_lakehouse_inventory",
    "load_lakehouse_inventory_from_descriptors",
    "load_transitional_lakehouse_inventory",
    "load_source_descriptor",
    "validate_lakehouse_descriptor",
    "validate_source_descriptor",
]
