name: sales_order_revenue
version: "1.0.0"
config-version: 2

profile: sales_order_revenue

model-paths: ["models"]
macro-paths: []
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  sales_order_revenue:
    +database: "{{ env_var('OPENLAKEFORGE_CATALOG_NAME', 'lakehouse_dev') }}"
    +materialized: table
    +on_table_exists: replace
    +meta:
      dagster:
        group: sales_order_revenue
    gold:
      +tags: ["sales", "order_revenue", "gold"]
