slice_name: Campaign Conversion Funnel
description: Purchases by campaign channel.
viz_type: pie
params:
  datasource: null
  viz_type: pie
  groupby:
  - channel
  metric: sum__purchase_count
  row_limit: 100
  number_format: SMART_NUMBER
  show_labels: true
  show_legend: true
  color_scheme: supersetColors
query_context: null
cache_timeout: null
uuid: 54bd16a6-da2c-51cb-8950-c54fbfcc1310
version: 1.0.0
dataset_uuid: 315fa5c7-9648-54c3-a08b-5d2c803e0ca7
