slice_name: Daily Revenue by Region
viz_type: echarts_timeseries_line
params:
  adhoc_filters: []
  annotation_layers: []
  bottom_margin: auto
  color_scheme: supersetColors
  comparison_type: values
  contribution: false
  datasource: 1__table
  granularity_sqla: sale_date
  groupby:
    - region
  label_colors: {}
  left_margin: auto
  line_interpolation: linear
  metrics:
    - aggregate: SUM
      column:
        column_name: gross_revenue
        expression: null
        filterable: true
        groupby: false
        is_dttm: false
        optionName: _col_gross_revenue
        python_date_format: null
        type: DOUBLE
        verbose_name: Gross revenue
      expressionType: SIMPLE
      hasCustomLabel: true
      isNew: false
      label: Gross revenue
      optionName: metric_gross_revenue
      sqlExpression: null
  order_desc: true
  queryFields:
    groupby: groupby
    metrics: metrics
  rich_tooltip: true
  rolling_type: None
  row_limit: null
  show_brush: auto
  show_legend: true
  show_markers: false
  time_grain_sqla: P1D
  time_range: No filter
  url_params: {}
  viz_type: echarts_timeseries_line
  x_axis_format: smart_date
  x_axis_label: Sale date
  x_axis_showminmax: true
  x_ticks_layout: auto
  y_axis_bounds:
    - null
    - null
  y_axis_format: SMART_NUMBER
  y_axis_label: Gross revenue
  y_axis_showminmax: true
cache_timeout: null
uuid: 37989f70-c78d-5658-ae58-0348fcc5e189
version: 1.0.0
dataset_uuid: d86370ee-5681-52aa-bf13-dd6751d21b35
