slice_name: Product Revenue and Margin
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters: []
  all_columns: []
  color_pn: true
  datasource: 1__table
  granularity_sqla: null
  groupby:
  - category
  - product_name
  metrics:
  - aggregate: SUM
    column:
      column_name: gross_revenue
      expression: null
      filterable: true
      groupby: false
      is_dttm: false
      optionName: _col_gross_revenue
      python_date_format: null
      type: DOUBLE
      verbose_name: Gross revenue
    expressionType: SIMPLE
    hasCustomLabel: true
    isNew: false
    label: Gross revenue
    optionName: metric_gross_revenue
    sqlExpression: null
  - aggregate: SUM
    column:
      column_name: gross_margin
      expression: null
      filterable: true
      groupby: false
      is_dttm: false
      optionName: _col_gross_margin
      python_date_format: null
      type: DOUBLE
      verbose_name: Gross margin
    expressionType: SIMPLE
    hasCustomLabel: true
    isNew: false
    label: Gross margin
    optionName: metric_gross_margin
    sqlExpression: null
  order_by_cols: []
  order_desc: true
  percent_metrics: null
  queryFields:
    groupby: groupby
    metrics: metrics
  query_mode: aggregate
  row_limit: 100
  show_cell_bars: true
  table_timestamp_format: smart_date
  time_grain_sqla: null
  time_range: No filter
  url_params: {}
  viz_type: table
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: f2dd6e77-9b3b-5102-81a9-9add209061d1
version: 1.0.0
dataset_uuid: 98f62c68-d375-541e-9c10-7b7c7084c22c
