name: sales_poc
version: "0.4.0"
config-version: 2

profile: sales_poc

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  sales_poc:
    +database: sales_dev
    +schema: gold
    +materialized: iceberg_table
    +meta:
      dagster:
        group: sales
    gold:
      +tags: ["sales", "gold"]
