apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "garage.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "garage.labels" . | nindent 4 }}
data:
  garage.toml: |
    metadata_dir = "/var/lib/garage/meta"
    data_dir     = "/var/lib/garage/data"
    db_engine    = {{ .Values.garage.dbEngine | quote }}

    replication_factor = {{ .Values.garage.replicationFactor }}

    rpc_bind_addr = "[::]:{{ .Values.service.rpcPort }}"
    rpc_secret    = {{ .Values.garage.rpcSecret | quote }}

    [s3_api]
    api_bind_addr = "[::]:{{ .Values.service.s3Port }}"
    s3_region     = {{ .Values.garage.s3Region | quote }}
    root_domain   = ""

    [admin]
    api_bind_addr = "[::]:{{ .Values.service.adminPort }}"
    admin_token   = {{ .Values.garage.adminToken | quote }}
