#!/usr/bin/env bash
# Load local runtime defaults from Terraform provider contracts when available.
#
# This file is intended to be sourced. It keeps local fallback values so tests
# and profile parsing still work before the stack is applied.

OPENLAKEFORGE_CONTRACT_TERRAFORM_DIR="${OPENLAKEFORGE_CONTRACT_TERRAFORM_DIR:-infra/terraform/environments/local}"
OPENLAKEFORGE_QUERY_SQLALCHEMY_URI_IS_USER_SET="${OPENLAKEFORGE_QUERY_SQLALCHEMY_URI+x}"
OPENMETADATA_CATALOG_SERVICE_IS_USER_SET="${OPENMETADATA_CATALOG_SERVICE+x}"
OPENLAKEFORGE_STORAGE_OM_SERVICE_IS_USER_SET="${OPENLAKEFORGE_STORAGE_OM_SERVICE+x}"
OPENLAKEFORGE_STORAGE_DISPLAY_NAME_IS_USER_SET="${OPENLAKEFORGE_STORAGE_DISPLAY_NAME+x}"

# Directory of this (sourced) file, used to locate sibling helper scripts.
OPENLAKEFORGE_CONTRACTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

set_default_contract_env() {
  local default_catalog_namespaces_json='[{"name":"sales_order_revenue_silver","location":"s3://lakehouse-silver/sales_order_revenue_silver/"},{"name":"sales_order_revenue_gold","location":"s3://lakehouse-gold/sales_order_revenue_gold/"},{"name":"sales_customer_health_silver","location":"s3://lakehouse-silver/sales_customer_health_silver/"},{"name":"sales_customer_health_gold","location":"s3://lakehouse-gold/sales_customer_health_gold/"},{"name":"supply_chain_inventory_reliability_silver","location":"s3://lakehouse-silver/supply_chain_inventory_reliability_silver/"},{"name":"supply_chain_inventory_reliability_gold","location":"s3://lakehouse-gold/supply_chain_inventory_reliability_gold/"}]'
  local default_catalog_silver_namespaces_json='{"sales_order_revenue":"sales_order_revenue_silver","sales_customer_health":"sales_customer_health_silver","supply_chain_inventory_reliability":"supply_chain_inventory_reliability_silver"}'
  local default_catalog_gold_namespaces_json='{"sales_order_revenue":"sales_order_revenue_gold","sales_customer_health":"sales_customer_health_gold","supply_chain_inventory_reliability":"supply_chain_inventory_reliability_gold"}'

  export OPENLAKEFORGE_STORAGE_LOGICAL_NAME="${OPENLAKEFORGE_STORAGE_LOGICAL_NAME:-lakehouse_storage}"
  export OPENLAKEFORGE_STORAGE_PROVIDER="${OPENLAKEFORGE_STORAGE_PROVIDER:-local}"
  export OPENLAKEFORGE_STORAGE_IMPLEMENTATION="${OPENLAKEFORGE_STORAGE_IMPLEMENTATION:-storage.s3_compatible.seaweedfs}"
  export OPENLAKEFORGE_STORAGE_TYPE="${OPENLAKEFORGE_STORAGE_TYPE:-s3}"
  export OPENLAKEFORGE_STORAGE_BRONZE_BUCKET="${OPENLAKEFORGE_STORAGE_BRONZE_BUCKET:-lakehouse-bronze}"
  export OPENLAKEFORGE_STORAGE_SILVER_BUCKET="${OPENLAKEFORGE_STORAGE_SILVER_BUCKET:-lakehouse-silver}"
  export OPENLAKEFORGE_STORAGE_GOLD_BUCKET="${OPENLAKEFORGE_STORAGE_GOLD_BUCKET:-lakehouse-gold}"
  export OPENLAKEFORGE_STORAGE_BUCKET="${OPENLAKEFORGE_STORAGE_BUCKET:-${OPENLAKEFORGE_STORAGE_BRONZE_BUCKET}}"
  export OPENLAKEFORGE_STORAGE_REGION="${OPENLAKEFORGE_STORAGE_REGION:-us-east-1}"
  export OPENLAKEFORGE_STORAGE_ENDPOINT="${OPENLAKEFORGE_STORAGE_ENDPOINT:-http://seaweedfs-s3:8333}"
  export OPENLAKEFORGE_STORAGE_VIRTUAL_HOST_ENDPOINT="${OPENLAKEFORGE_STORAGE_VIRTUAL_HOST_ENDPOINT:-http://lakehouse.svc.cluster.local:8333}"
  export OPENLAKEFORGE_STORAGE_PATH_STYLE_ACCESS="${OPENLAKEFORGE_STORAGE_PATH_STYLE_ACCESS:-true}"
  export OPENLAKEFORGE_STORAGE_SSL_MODE="${OPENLAKEFORGE_STORAGE_SSL_MODE:-disabled}"
  export OPENLAKEFORGE_STORAGE_CREDENTIALS_SECRET_NAME="${OPENLAKEFORGE_STORAGE_CREDENTIALS_SECRET_NAME:-seaweedfs-s3-creds}"
  export OPENLAKEFORGE_STORAGE_ACCESS_KEY_ID_KEY="${OPENLAKEFORGE_STORAGE_ACCESS_KEY_ID_KEY:-AWS_ACCESS_KEY_ID}"
  export OPENLAKEFORGE_STORAGE_SECRET_ACCESS_KEY_KEY="${OPENLAKEFORGE_STORAGE_SECRET_ACCESS_KEY_KEY:-AWS_SECRET_ACCESS_KEY}"
  export OPENLAKEFORGE_STORAGE_S3_SERVICE_NAME="${OPENLAKEFORGE_STORAGE_S3_SERVICE_NAME:-seaweedfs-s3}"
  export OPENLAKEFORGE_STORAGE_S3_SERVICE_PORT="${OPENLAKEFORGE_STORAGE_S3_SERVICE_PORT:-8333}"

  export OPENLAKEFORGE_CATALOG_LOGICAL_NAME="${OPENLAKEFORGE_CATALOG_LOGICAL_NAME:-iceberg_catalog}"
  export OPENLAKEFORGE_CATALOG_IMPLEMENTATION="${OPENLAKEFORGE_CATALOG_IMPLEMENTATION:-catalog.iceberg_rest.polaris}"
  export OPENLAKEFORGE_CATALOG_TYPE="${OPENLAKEFORGE_CATALOG_TYPE:-rest}"
  export OPENLAKEFORGE_CATALOG_PROVIDER="${OPENLAKEFORGE_CATALOG_PROVIDER:-polaris}"
  export OPENLAKEFORGE_CATALOG_NAME="${OPENLAKEFORGE_CATALOG_NAME:-lakehouse_dev}"
  export OPENLAKEFORGE_CATALOG_RUNTIME_PROFILE="${OPENLAKEFORGE_CATALOG_RUNTIME_PROFILE:-polaris-rest}"
  export OPENLAKEFORGE_CATALOG_REST_URI="${OPENLAKEFORGE_CATALOG_REST_URI:-http://polaris:8181/api/catalog}"
  export OPENLAKEFORGE_CATALOG_TOKEN_URI="${OPENLAKEFORGE_CATALOG_TOKEN_URI:-http://polaris:8181/api/catalog/v1/oauth/tokens}"
  export OPENLAKEFORGE_CATALOG_OAUTH_SCOPE="${OPENLAKEFORGE_CATALOG_OAUTH_SCOPE:-PRINCIPAL_ROLE:ALL}"
  export OPENLAKEFORGE_CATALOG_WAREHOUSE="${OPENLAKEFORGE_CATALOG_WAREHOUSE:-lakehouse_dev}"
  export OPENLAKEFORGE_CATALOG_GLUE_REGION="${OPENLAKEFORGE_CATALOG_GLUE_REGION:-}"
  export OPENLAKEFORGE_CATALOG_GLUE_CATALOG_ID="${OPENLAKEFORGE_CATALOG_GLUE_CATALOG_ID:-}"
  export OPENLAKEFORGE_CATALOG_GLUE_REST_URI="${OPENLAKEFORGE_CATALOG_GLUE_REST_URI:-}"
  export OPENLAKEFORGE_CATALOG_GLUE_REST_WAREHOUSE="${OPENLAKEFORGE_CATALOG_GLUE_REST_WAREHOUSE:-${OPENLAKEFORGE_CATALOG_GLUE_CATALOG_ID}}"
  export OPENLAKEFORGE_CATALOG_GLUE_DATABASE="${OPENLAKEFORGE_CATALOG_GLUE_DATABASE:-}"
  export OPENLAKEFORGE_CATALOG_GLUE_WAREHOUSE_PREFIX="${OPENLAKEFORGE_CATALOG_GLUE_WAREHOUSE_PREFIX:-warehouse/iceberg}"
  export OPENLAKEFORGE_CATALOG_NAMESPACE_MODEL="${OPENLAKEFORGE_CATALOG_NAMESPACE_MODEL:-product-layer}"
  export OPENLAKEFORGE_CATALOG_NAMESPACES_JSON="${OPENLAKEFORGE_CATALOG_NAMESPACES_JSON:-${default_catalog_namespaces_json}}"
  export OPENLAKEFORGE_CATALOG_SILVER_NAMESPACES_JSON="${OPENLAKEFORGE_CATALOG_SILVER_NAMESPACES_JSON:-${default_catalog_silver_namespaces_json}}"
  export OPENLAKEFORGE_CATALOG_GOLD_NAMESPACES_JSON="${OPENLAKEFORGE_CATALOG_GOLD_NAMESPACES_JSON:-${default_catalog_gold_namespaces_json}}"
  export OPENLAKEFORGE_CATALOG_SILVER_NAMESPACE="${OPENLAKEFORGE_CATALOG_SILVER_NAMESPACE:-}"
  export OPENLAKEFORGE_CATALOG_GOLD_NAMESPACE="${OPENLAKEFORGE_CATALOG_GOLD_NAMESPACE:-}"
  export OPENLAKEFORGE_CATALOG_FLOE_CREDENTIALS_SECRET_NAME="${OPENLAKEFORGE_CATALOG_FLOE_CREDENTIALS_SECRET_NAME:-polaris-floe-creds}"
  export OPENLAKEFORGE_CATALOG_FLOE_CLIENT_ID_KEY="${OPENLAKEFORGE_CATALOG_FLOE_CLIENT_ID_KEY:-POLARIS_FLOE_CLIENT_ID}"
  export OPENLAKEFORGE_CATALOG_FLOE_CLIENT_SECRET_KEY="${OPENLAKEFORGE_CATALOG_FLOE_CLIENT_SECRET_KEY:-POLARIS_FLOE_CLIENT_SECRET}"
  export OPENLAKEFORGE_CATALOG_DBT_CREDENTIALS_SECRET_NAME="${OPENLAKEFORGE_CATALOG_DBT_CREDENTIALS_SECRET_NAME:-polaris-dbt-creds}"
  export OPENLAKEFORGE_CATALOG_DBT_CLIENT_ID_KEY="${OPENLAKEFORGE_CATALOG_DBT_CLIENT_ID_KEY:-POLARIS_DBT_CLIENT_ID}"
  export OPENLAKEFORGE_CATALOG_DBT_CLIENT_SECRET_KEY="${OPENLAKEFORGE_CATALOG_DBT_CLIENT_SECRET_KEY:-POLARIS_DBT_CLIENT_SECRET}"

  export OPENLAKEFORGE_OPS_BUCKET_NAME="${OPENLAKEFORGE_OPS_BUCKET_NAME:-${OPENLAKEFORGE_ARTIFACT_BUCKET_NAME:-openlakeforge-ops}}"
  export OPENLAKEFORGE_ARTIFACT_BUCKET_NAME="${OPENLAKEFORGE_ARTIFACT_BUCKET_NAME:-${OPENLAKEFORGE_OPS_BUCKET_NAME}}"
  export OPENLAKEFORGE_ARTIFACT_BASE_URI="${OPENLAKEFORGE_ARTIFACT_BASE_URI:-s3://${OPENLAKEFORGE_ARTIFACT_BUCKET_NAME}}"
  export OPENLAKEFORGE_FLOE_MANIFEST_ACCESS_MODE="${OPENLAKEFORGE_FLOE_MANIFEST_ACCESS_MODE:-remote}"
  export OPENLAKEFORGE_FLOE_MANIFEST_BASE_URI="${OPENLAKEFORGE_FLOE_MANIFEST_BASE_URI:-${OPENLAKEFORGE_ARTIFACT_BASE_URI}/floe/manifests}"
  export OPENLAKEFORGE_FLOE_REPORT_BASE_URI="${OPENLAKEFORGE_FLOE_REPORT_BASE_URI:-${OPENLAKEFORGE_ARTIFACT_BASE_URI}/floe/reports}"
  export OPENLAKEFORGE_LOG_BASE_URI="${OPENLAKEFORGE_LOG_BASE_URI:-${OPENLAKEFORGE_ARTIFACT_BASE_URI}/logs}"
  export OPENLAKEFORGE_RUN_ARTIFACT_BASE_URI="${OPENLAKEFORGE_RUN_ARTIFACT_BASE_URI:-${OPENLAKEFORGE_ARTIFACT_BASE_URI}/run-artifacts}"
  export OPENLAKEFORGE_ARTIFACT_LOCAL_UPLOAD_ACCESS_MODE="${OPENLAKEFORGE_ARTIFACT_LOCAL_UPLOAD_ACCESS_MODE:-kubectl-port-forward}"
  export OPENLAKEFORGE_QUERY_TRINO_HOST="${OPENLAKEFORGE_QUERY_TRINO_HOST:-trino}"
  export OPENLAKEFORGE_QUERY_TRINO_PORT="${OPENLAKEFORGE_QUERY_TRINO_PORT:-8080}"
  export OPENLAKEFORGE_QUERY_TRINO_CATALOG="${OPENLAKEFORGE_QUERY_TRINO_CATALOG:-iceberg}"

  export OPENLAKEFORGE_KUBE_NAMESPACE="${OPENLAKEFORGE_KUBE_NAMESPACE:-${NAMESPACE:-lakehouse}}"

  export AWS_REGION="${AWS_REGION:-${OPENLAKEFORGE_STORAGE_REGION}}"
  export AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION:-${AWS_REGION}}"
  if [[ "${OPENLAKEFORGE_STORAGE_IMPLEMENTATION}" == "storage.aws_s3" ]]; then
    unset AWS_ENDPOINT_URL_S3
    unset OPENLAKEFORGE_DUCKDB_S3_ENDPOINT
    export AWS_S3_FORCE_PATH_STYLE="${AWS_S3_FORCE_PATH_STYLE:-false}"
  else
    export AWS_ENDPOINT_URL_S3="${AWS_ENDPOINT_URL_S3:-${OPENLAKEFORGE_STORAGE_ENDPOINT}}"
    export OPENLAKEFORGE_DUCKDB_S3_ENDPOINT="${OPENLAKEFORGE_DUCKDB_S3_ENDPOINT:-${OPENLAKEFORGE_STORAGE_ENDPOINT#http://}}"
    export AWS_S3_FORCE_PATH_STYLE="${AWS_S3_FORCE_PATH_STYLE:-${OPENLAKEFORGE_STORAGE_PATH_STYLE_ACCESS}}"
  fi
  if [[ "${OPENLAKEFORGE_STORAGE_SSL_MODE}" == "disabled" ]]; then
    export AWS_ALLOW_HTTP="${AWS_ALLOW_HTTP:-true}"
  fi

  # Compatibility names for current Polaris REST consumers.
  export POLARIS_REST_URI="${POLARIS_REST_URI:-${OPENLAKEFORGE_CATALOG_REST_URI}}"
  export POLARIS_TOKEN_URI="${POLARIS_TOKEN_URI:-${OPENLAKEFORGE_CATALOG_TOKEN_URI}}"
  export POLARIS_WAREHOUSE="${POLARIS_WAREHOUSE:-${OPENLAKEFORGE_CATALOG_WAREHOUSE}}"
  export POLARIS_OAUTH_SCOPE="${POLARIS_OAUTH_SCOPE:-${OPENLAKEFORGE_CATALOG_OAUTH_SCOPE}}"
  export OPENLAKEFORGE_CATALOG_DBT_CLIENT_ID="${OPENLAKEFORGE_CATALOG_DBT_CLIENT_ID:-${POLARIS_DBT_CLIENT_ID:-openlakeforge-dbt}}"
  export OPENLAKEFORGE_CATALOG_DBT_CLIENT_SECRET="${OPENLAKEFORGE_CATALOG_DBT_CLIENT_SECRET:-${POLARIS_DBT_CLIENT_SECRET:-openlakeforge-dbt}}"
}

set_default_contract_env

if command -v terraform >/dev/null 2>&1 &&
  command -v python3 >/dev/null 2>&1 &&
  [[ -d "${OPENLAKEFORGE_CONTRACT_TERRAFORM_DIR}" ]] &&
  terraform -chdir="${OPENLAKEFORGE_CONTRACT_TERRAFORM_DIR}" output -json provider_contracts >/tmp/openlakeforge-provider-contracts.json 2>/dev/null; then
  python3 "${OPENLAKEFORGE_CONTRACTS_DIR}/emit-contract-env.py" \
    /tmp/openlakeforge-provider-contracts.json >/tmp/openlakeforge-contract-env.sh
  source /tmp/openlakeforge-contract-env.sh

  set_default_contract_env
fi

if [[ "${OPENLAKEFORGE_STORAGE_IMPLEMENTATION}" == "storage.aws_s3" ]]; then
  export OPENLAKEFORGE_STORAGE_ENDPOINT=""
  export OPENLAKEFORGE_STORAGE_VIRTUAL_HOST_ENDPOINT=""
  export OPENLAKEFORGE_STORAGE_PATH_STYLE_ACCESS="false"
  export OPENLAKEFORGE_STORAGE_CREDENTIALS_SECRET_NAME=""
  export OPENLAKEFORGE_STORAGE_ACCESS_KEY_ID_KEY=""
  export OPENLAKEFORGE_STORAGE_SECRET_ACCESS_KEY_KEY=""
  export OPENLAKEFORGE_STORAGE_S3_SERVICE_NAME=""
  export OPENLAKEFORGE_STORAGE_S3_SERVICE_PORT=""
  unset AWS_ENDPOINT_URL_S3
  unset OPENLAKEFORGE_DUCKDB_S3_ENDPOINT
  export AWS_S3_FORCE_PATH_STYLE="${AWS_S3_FORCE_PATH_STYLE:-false}"
fi
if [[ "${OPENLAKEFORGE_CATALOG_TYPE}" == "glue" && "${OPENLAKEFORGE_CATALOG_PROVIDER}" == "aws-glue" ]]; then
  export OPENLAKEFORGE_CATALOG_GLUE_DATABASE="${OPENLAKEFORGE_CATALOG_GLUE_DATABASE:-}"
  export OPENLAKEFORGE_CATALOG_WAREHOUSE="${OPENLAKEFORGE_CATALOG_NAME}"
  export OPENLAKEFORGE_CATALOG_GLUE_REST_WAREHOUSE="${OPENLAKEFORGE_CATALOG_GLUE_REST_WAREHOUSE:-${OPENLAKEFORGE_CATALOG_GLUE_CATALOG_ID}}"
  export OPENLAKEFORGE_CATALOG_GLUE_WAREHOUSE_PREFIX="${OPENLAKEFORGE_CATALOG_GLUE_WAREHOUSE_PREFIX:-warehouse/iceberg}"
  export OPENLAKEFORGE_CATALOG_TOKEN_URI=""
  export OPENLAKEFORGE_CATALOG_OAUTH_SCOPE=""
  export OPENLAKEFORGE_CATALOG_FLOE_CREDENTIALS_SECRET_NAME=""
  export OPENLAKEFORGE_CATALOG_FLOE_CLIENT_ID_KEY=""
  export OPENLAKEFORGE_CATALOG_FLOE_CLIENT_SECRET_KEY=""
  export OPENLAKEFORGE_CATALOG_DBT_CREDENTIALS_SECRET_NAME=""
  export OPENLAKEFORGE_CATALOG_DBT_CLIENT_ID_KEY=""
  export OPENLAKEFORGE_CATALOG_DBT_CLIENT_SECRET_KEY=""
fi

OPENLAKEFORGE_CATALOG_OM_SERVICE_NAME="polaris"
if [[ "${OPENLAKEFORGE_CATALOG_TYPE}" == "glue" && "${OPENLAKEFORGE_CATALOG_PROVIDER}" == "aws-glue" ]]; then
  OPENLAKEFORGE_CATALOG_OM_SERVICE_NAME="aws_glue"
fi
OPENLAKEFORGE_DEFAULT_CATALOG_DATABASE_FQN="${OPENLAKEFORGE_CATALOG_OM_SERVICE_NAME}.${OPENLAKEFORGE_CATALOG_NAME}"
OPENLAKEFORGE_DEFAULT_CATALOG_SILVER_SCHEMA_FQNS_JSON="{\"sales_order_revenue\":\"${OPENLAKEFORGE_DEFAULT_CATALOG_DATABASE_FQN}.sales_order_revenue_silver\",\"sales_customer_health\":\"${OPENLAKEFORGE_DEFAULT_CATALOG_DATABASE_FQN}.sales_customer_health_silver\",\"supply_chain_inventory_reliability\":\"${OPENLAKEFORGE_DEFAULT_CATALOG_DATABASE_FQN}.supply_chain_inventory_reliability_silver\"}"
OPENLAKEFORGE_DEFAULT_CATALOG_GOLD_SCHEMA_FQNS_JSON="{\"sales_order_revenue\":\"${OPENLAKEFORGE_DEFAULT_CATALOG_DATABASE_FQN}.sales_order_revenue_gold\",\"sales_customer_health\":\"${OPENLAKEFORGE_DEFAULT_CATALOG_DATABASE_FQN}.sales_customer_health_gold\",\"supply_chain_inventory_reliability\":\"${OPENLAKEFORGE_DEFAULT_CATALOG_DATABASE_FQN}.supply_chain_inventory_reliability_gold\"}"
if [[ -z "${OPENLAKEFORGE_CATALOG_DATABASE_FQN:-}" ]]; then
  export OPENLAKEFORGE_CATALOG_DATABASE_FQN="${OPENLAKEFORGE_DEFAULT_CATALOG_DATABASE_FQN}"
fi
if [[ -z "${OPENLAKEFORGE_CATALOG_SILVER_SCHEMA_FQNS_JSON:-}" ]]; then
  export OPENLAKEFORGE_CATALOG_SILVER_SCHEMA_FQNS_JSON="${OPENLAKEFORGE_DEFAULT_CATALOG_SILVER_SCHEMA_FQNS_JSON}"
fi
if [[ -z "${OPENLAKEFORGE_CATALOG_GOLD_SCHEMA_FQNS_JSON:-}" ]]; then
  export OPENLAKEFORGE_CATALOG_GOLD_SCHEMA_FQNS_JSON="${OPENLAKEFORGE_DEFAULT_CATALOG_GOLD_SCHEMA_FQNS_JSON}"
fi
if [[ -z "${OPENMETADATA_CATALOG_SERVICE_IS_USER_SET}" ]]; then
  export OPENMETADATA_CATALOG_SERVICE="${OPENLAKEFORGE_CATALOG_OM_SERVICE_NAME}"
fi
if [[ "${OPENLAKEFORGE_STORAGE_IMPLEMENTATION}" == "storage.aws_s3" ]]; then
  if [[ -z "${OPENLAKEFORGE_STORAGE_OM_SERVICE_IS_USER_SET}" ]]; then
    export OPENLAKEFORGE_STORAGE_OM_SERVICE="aws_s3"
  fi
  if [[ -z "${OPENLAKEFORGE_STORAGE_DISPLAY_NAME_IS_USER_SET}" ]]; then
    export OPENLAKEFORGE_STORAGE_DISPLAY_NAME="AWS S3"
  fi
else
  if [[ -z "${OPENLAKEFORGE_STORAGE_OM_SERVICE_IS_USER_SET}" ]]; then
    export OPENLAKEFORGE_STORAGE_OM_SERVICE="seaweedfs"
  fi
  if [[ -z "${OPENLAKEFORGE_STORAGE_DISPLAY_NAME_IS_USER_SET}" ]]; then
    export OPENLAKEFORGE_STORAGE_DISPLAY_NAME="SeaweedFS S3"
  fi
fi

export CODE_BUCKET_NAME="${CODE_BUCKET_NAME:-${OPENLAKEFORGE_ARTIFACT_BUCKET_NAME}}"
export OPENMETADATA_CATALOG_DATABASE="${OPENMETADATA_CATALOG_DATABASE:-${OPENLAKEFORGE_CATALOG_NAME}}"
if [[ -z "${OPENLAKEFORGE_QUERY_SQLALCHEMY_URI_IS_USER_SET}" ]]; then
  export OPENLAKEFORGE_QUERY_SQLALCHEMY_URI="trino://superset@${OPENLAKEFORGE_QUERY_TRINO_HOST}:${OPENLAKEFORGE_QUERY_TRINO_PORT}/${OPENLAKEFORGE_QUERY_TRINO_CATALOG}"
fi
